version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    versioning-strategy: increase
    labels:
      - 'dependencies'
    cooldown:
      semver-major-days: 30
      semver-minor-days: 7
      semver-patch-days: 3
    groups:
      docusaurus:
        patterns:
          - '@docusaurus/*'
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
    labels:
      - 'dependencies'
