name: all

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          cache: npm
      - run: npm ci -w pkgs/typed-api-spec
      - run: npm run build  -w pkgs/typed-api-spec
      - run: npm test -w pkgs/typed-api-spec
  doc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          cache: npm
      - uses: actions/configure-pages@45bfe0192ca1faeb007ade9deae92b16b8254a0d # v6.0.0
      - run: npm ci -w pkgs/docs
      - run: npm run build -w pkgs/docs
  examples:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          cache: npm
      - run: npm ci
      - run: npm run build -w pkgs/typed-api-spec
      - run: npm test -w examples/misc
      - run: npm run build -w examples/vite
      - run: npm run build -w examples/vite-react-openapi
